http:
  port: "8081"

autodiscovery:
  id: "2191635"
  
address: 
  notification:
    sender: "fnextnotificationservice@florencenext.com"
  fallbackAlert:
    sender: "fnextnotificationservice@florencenext.com"
    receiver: "areasistemi@florencenext.com"
    
smtp:
  gmail:
    host: "smtp-relay.gmail.com"
    port: "465"
    user: "acanale@florencenext.com"
    password: ""
  office365:
    host: "smtp.office365.com"
    port: "587"
    user: "andrea.canale@siroccogroup.com"
    password: ""
  sendgrid:
    host: "smtp.sendgrid.net"
    port: "465"
    user: "apikey"
    password: ""